apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-container
        image: nashon11/capstone-app:v2
        ports:
        - containerPort: 80
