apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: capstone-rollout
  namespace: capstone
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100
