apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rollout
  namespace: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-container
        image: nginx:1.20
