apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nashon11/capstone-gitops.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
