apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: capstone
spec:
  type: NodePort
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
