name: Verify Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List files
        run: |
          echo "Current directory:"
          pwd
          ls -la
          echo "Workflows directory:"
          ls -la .github/workflows/
      
      - name: Simple test
        run: echo "✅ Workflow is working!"
